# Generated by Django 6.0.7 on 2026-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_providerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
