# Generated by Django 6.0.7 on 2026-07-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_providerprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', max_length=200),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
