# Generated by Django 6.0.7 on 2026-07-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_providerprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProviderGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_pics/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='accounts.providerprofile')),
            ],
        ),
    ]
