# Generated by Django 6.0.7 on 2026-07-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_providerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
