# Generated by Django 6.0.7 on 2026-07-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
