# Generated by Django 6.0.7 on 2026-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS Latitude', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS Longitude', null=True),
        ),
    ]
