# Generated by Django 6.0.7 on 2026-07-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on Service'), ('upi', 'UPI')], default='card', max_length=50),
        ),
    ]
