# Generated by Django 6.0.7 on 2026-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on Service'), ('upi', 'UPI')], default='cash', max_length=50),
        ),
    ]
