# Generated by Django 6.0.7 on 2026-07-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_provideravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='problem_photo',
            field=models.ImageField(blank=True, null=True, upload_to='booking_photos/'),
        ),
    ]
