# Generated by Django 6.0.6 on 2026-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_booking_problem_description_booking_problem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='pricing_type',
            field=models.CharField(choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Charge')], default='hourly', help_text='Whether the price is per hour or a fixed/full charge', max_length=10),
        ),
    ]
