# Generated by Django 6.0.6 on 2026-08-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_providerservice_pricing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='default_pricing_type',
            field=models.CharField(choices=[('hourly', 'Hourly Rate'), ('fixed', 'Fixed Charge')], default='fixed', help_text='Standard pricing metric suitable for this profession', max_length=10),
        ),
    ]
